# Basic settings
url: "https://www.netjapa.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog


description: "Tenha um site profissional e personalizado para você ou 
para sua empresa com a NETJAPA.COM. Criamos sites, loja virtual e apps. Venha - Paraty"

tagline: "Criar site, desenvolvimento de site, app android, site, 
 aplicativo, e-commerce, loja virtual, Paraty, Paraty-RJ, Costa Verde, NETJAPA.COM"


title: "Criar Site Profissional, Loja Virtual e App na NETJAPA.COM"
timezone: America/Sao_Paulo
lang: pt-br
# Build settings
markdown: kramdown

# Kramdown options
kramdown:
  # Prevent IDs from being added to h1-h6 tags
  auto_ids: false

plugins:

  - jekyll-seo-tag
  #- jekyll-multiple-languages-plugin
  - jekyll-menus
  - jemoji
  - jekyll-sitemap


source: .
destination: ./_site
# Compress CSS
sass:
  style: :compressed
  sass_dir: _sass

#Permalink format (/blog/ is ignored for pages)
#permalink: /post/:title
#permalink: :slug/

#Collections
collections:
  slides:
  services:
include:
  - _pages
  - _posts
  - _services
section: true

# set to 'true' to enable Netlify CMS (/admin) in production builds
netlifycms: false

# set to 'true' to enable Google Analytics tracking code in production builds
analytics: false

# Compress HTML (in liquid via layouts/compress.html)
compress_html:
  clippings: all


#languages: ["pt-br", "en"]
#exclude_from_localizations: ["assets", "_sass",  "photos"]
#defaultLang: pt-br

  
# Social

social:
  name: Netjapa
  links:
    - https://twitter.com/netjapa
    - https://www.facebook.com/netjapa

# set some common post defaults
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post" # set the correct default template for a post
      section: "post" # set the root section name

# Include in processing (e.g. Netlify directives)
# Uncomment before use

#include:
#  - _redirects
#  - _headers

# Exclude from processing.
# The following items will not be processed.
exclude:
  - README.md
  - LICENSE.txt
  - netlify.toml
  - feed.xml
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
